name: CI

on:
- push
- pull_request

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ['*', 'lts/*']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Lint Source
        run: pnpm run --if-present lint

      - name: Build Source
        run: pnpm run --if-present build

      - name: Test Source
        run: pnpm run --if-present test
